services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: lovelace-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SPRING_DATA_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SPRING_DATA_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - lovelace-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: lovelace-redis-dev
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${SPRING_DATA_REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - lovelace-network

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lovelace-api-dev
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - maven_cache:/root/.m2
    networks:
      - lovelace-network
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    stdin_open: true
    tty: true

networks:
  lovelace-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  maven_cache:
