FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY boardgames_ranks.csv ./boardgames_ranks.csv

COPY src ./src

EXPOSE 8080
# Debug port
EXPOSE 5005 

CMD ["mvn", "spring-boot:run"]
